
export const LABELS_ZH = {
  APP_TITLE: "备货小助手",
  UPLOAD_TITLE: "上传新的订购订单",
  UPLOAD_FILE: "选择 TXT 文件",
  FILE_FORMAT_NOTE: "文件格式: 零件号,零件名,数量,备注 (每行一个零件,逗号分隔)",
  EXISTING_ORDERS: "已存在的订单",
  NO_ORDERS: "暂无订单记录。",
  ORDER_NAME: "订单名称",
  UPLOAD_DATE: "上传日期",
  FILE_NAME: "文件名",
  VIEW_DETAILS: "查看详情",
  DELETE_ORDER: "删除订单",
  RENAME_ORDER: "重命名订单",
  SAVE_ORDER_NAME: "保存名称",
  EDIT_ORDER_NAME: "编辑订单名称",
  CANCEL_EDIT: "取消编辑",

  BACK_TO_ORDERS: "返回订单列表",
  BACK_TO_HOME: "返回主页",
  ORDER_DETAILS_FOR: "订单详情: ",
  ADD_PART: "添加零件",
  SAVE_CHANGES: "保存更改", // Generic, might be replaced by more specific
  PART_DETAILS: "零件详情",

  COLUMN_PART_NUMBER: "零件号", // In CSV export context, this will now mean Inventory Part Number
  COLUMN_PART_NAME: "零件名",
  COLUMN_QUANTITY: "数量",
  COLUMN_NOTES: "备注",
  COLUMN_SUPPLIER: "采购厂家",
  COLUMN_PURCHASER: "采购员",
  COLUMN_ESTIMATED_SHIPPING_DATE: "预计发货时间",
  COLUMN_IS_ARRIVED: "是否到货",
  COLUMN_IS_ORDER_COMPLETE: "是否完成订货",
  COLUMN_ACTIONS: "操作",
  COLUMN_STOCK_CHECK: "库存查询", 

  COLUMN_PART_NAME_CN: "零件中文名",
  COLUMN_VEHICLE_MODEL: "车型号",
  COLUMN_ORIGIN: "产地",
  COLUMN_UNIT: "单位",

  EDIT_NOTES: "编辑备注",
  NOTES_MODAL_TITLE_PREFIX: "零件备注: ",
  ADD_IMAGE: "添加图片",
  TEXT_NOTE_LABEL: "文本备注",
  IMAGE_PREVIEW: "图片预览",
  DELETE_IMAGE: "删除图片",
  NO_IMAGES_UPLOADED: "未上传任何图片。",
  MAX_IMAGES_REACHED: "最多只能上传 {maxCount} 张图片。",
  IMAGE_TOO_LARGE: "图片大小不能超过 {maxSizeMB}MB。",
  SAVE_NOTES: "保存备注",
  CLOSE_MODAL: "关闭",

  DELETE_PART: "移至回收站",
  CONFIRM_DELETE_ORDER_TITLE: "确认移至回收站",
  CONFIRM_DELETE_ORDER_MSG: "您确定要将此订单移至回收站吗？之后可以从回收站恢复。",
  CONFIRM_DELETE_PART_TITLE: "确认移至回收站",
  CONFIRM_DELETE_PART_MSG: "您确定要将此零件移至回收站吗？之后可以从订单详情页的回收部件列表中恢复。",
  CANCEL: "取消",
  CONFIRM: "确认",

  ERROR_FILE_READ: "文件读取或上传失败。",
  ERROR_API_GENERAL: "与服务器通信时发生错误，请稍后再试。",
  SUCCESS_ORDER_UPLOADED: "订单已成功上传！",
  SUCCESS_OPERATION: "操作成功！",

  CONFIRM_CHANGE_TITLE: "确认更改",
  CONFIRM_CHANGE_MESSAGE_PART: "您确定要将零件 \"{partName}\" 的 \"{field}\" 状态更改为 \"{value}\" 吗？",
  RESTORE: "恢复",
  PERMANENTLY_DELETE: "彻底删除",
  RECYCLE_BIN_TITLE: "回收站",
  NO_RECYCLED_ORDERS: "回收站是空的。",
  RECYCLED_PARTS_TITLE: "回收的部件 (本订单内)",
  NO_RECYCLED_PARTS: "此订单没有回收的部件。",
  DOWNLOAD_IMAGE: "下载图片",
  IMAGE_PREVIEW_TITLE: "图片预览",
  VIEW_RECYCLED_IMAGE: "查看图片",
  
  CONFIRM_RESTORE_ORDER_TITLE: "确认恢复订单",
  CONFIRM_RESTORE_ORDER_MSG: "您确定要恢复此订单吗？",
  CONFIRM_PERMANENTLY_DELETE_ORDER_TITLE: "确认彻底删除订单",
  CONFIRM_PERMANENTLY_DELETE_ORDER_MSG: "您确定要彻底删除此订单吗？此操作无法撤销。",

  CONFIRM_RESTORE_PART_TITLE: "确认恢复零件",
  CONFIRM_RESTORE_PART_MSG: "您确定要恢复此零件吗？",
  CONFIRM_PERMANENTLY_DELETE_PART_TITLE: "确认彻底删除零件",
  CONFIRM_PERMANENTLY_DELETE_PART_MSG: "您确定要彻底删除此零件吗？此操作无法撤销。",
  DELETED_ON: "删除于",

  LOGIN_TITLE: "用户登录",
  REGISTER_TITLE: "用户注册",
  USERNAME_LABEL: "用户名",
  EMAIL_LABEL: "邮箱地址",
  PASSWORD_LABEL: "密码",
  LOGIN_BUTTON: "登录",
  REGISTER_BUTTON: "注册",
  LOGOUT_BUTTON: "登出",
  ALREADY_HAVE_ACCOUNT: "已有账户？",
  NO_ACCOUNT_YET: "还没有账户？",
  LOGIN_PROMPT: "会话已过期或无效，请重新登录以继续。",
  REGISTER_HERE: "在此注册",
  LOGIN_HERE: "在此登录",
  LOADING: "加载中...",
  ERROR_INVALID_CREDENTIALS: "用户名或密码错误。",
  ERROR_REGISTRATION_FAILED: "注册失败，请稍后再试。",
  ERROR_EMAIL_IN_USE: "该邮箱已被注册。",
  ERROR_USERNAME_IN_USE: "该用户名已被使用。",
  LOADING_ORDER_DETAILS: "正在加载订单详情...", 

  LOGIN_IDENTIFIER_LABEL: "用户名或邮箱",
  POST_REGISTRATION_TITLE: "注册成功！您的新账户已创建",
  POST_REGISTRATION_EMAIL_LABEL: "您的新邮箱地址",
  POST_REGISTRATION_PASSWORD_HINT_LABEL: "密码提示",
  POST_REGISTRATION_INSTRUCTIONS: "请妥善保管您的新邮箱地址。您可以使用用户名或此邮箱地址登录，您的邮箱密码与网站登录密码相同。",
  POST_REGISTRATION_CONFIRM_BUTTON: "我已了解",
  COPY_BUTTON: "复制",
  COPIED_BUTTON: "已复制 ✓",

  INVENTORY_SEARCH_TITLE: "库存查询",
  SEARCH_BUTTON: "搜索",
  SEARCHING_BUTTON: "查询中...", 
  SEARCH_PART_NUMBER_LABEL: "零件号",
  SEARCH_PART_NUMBER_PLACEHOLDER: "输入零件号进行搜索...",
  NO_INVENTORY_RESULTS: "未找到匹配的零件。",
  INVENTORY_STOCK_QUANTITY: "库存数", 
  ERROR_INVENTORY_SEARCH: "库存查询失败，请稍后再试。",
  CHECK_STOCK_BUTTON: "查库存", 
  NOT_FOUND: "未找到",
  STOCK_CHECK_MODAL_TITLE_PREFIX: "库存查询结果: ", 
  NO_SIMILAR_PARTS_FOUND: "未找到相关零件库存信息。", 
  MATCHED_PART_LABEL: "(精确匹配)",

  VIEW_PRECISE_DETAILS_BUTTON: "查看精确详情",
  PART_DETAILS_MODAL_TITLE_PREFIX: "零件详情: ",
  ERROR_FETCHING_PART_DETAILS: "查询零件详情失败。",
  NO_PART_DETAILS_AVAILABLE: "未能加载此零件的详细信息。",
  PART_INFORMATION_LABEL: "零件信息",

  // New for OrderDetails redesign
  EDIT_MODE: "编辑",
  SAVE_CHANGES_BUTTON: "保存更改",
  CANCEL_EDIT_MODE: "放弃更改并退出编辑", // More descriptive for unsaved changes
  FINISH_EDIT_MODE: "完成编辑", // When no changes, or after save
  EXPORT_BUTTON: "导出库存详情 (CSV)",
  BATCH_STOCK_CHECK_BUTTON: "批量查库存",
  UNSAVED_CHANGES_TITLE: "未保存的更改",
  UNSAVED_CHANGES_MESSAGE: "您有未保存的更改。确定要放弃这些更改吗？",
  SAVING_CHANGES: "正在保存更改...",
  EXPORTING_DATA: "正在导出数据...",
  BATCH_CHECKING_STOCK: "正在批量查询库存...",
  BATCH_STOCK_VIEW_MODAL_TITLE: "批量库存查询结果 (订单: ", // Appended by order name
  NO_PARTS_FOR_BATCH_STOCK: "订单中没有零件可供批量查询库存。",
  ADDING_PART: "正在添加零件...",
  DELETING_PART: "正在移至回收站...",
  RESTORING_PART: "正在恢复零件...",
  DELETING_PART_PERMANENTLY: "正在彻底删除零件...",
  UPDATING_MONITORING_SETTINGS: "正在更新监控设置...",

  // New CSV Export Columns
  COLUMN_ORDER_PART_NUMBER_ORIGINAL: "订单原零件号",
  COLUMN_ORDER_PART_NAME_ORIGINAL: "订单原名称",

  // New Monitoring Columns & Labels
  COLUMN_INITIAL_STOCK: "初始库存",
  COLUMN_LATEST_STOCK: "最新库存",
  COLUMN_LAST_STOCK_CHECK: "上次检查",
  COLUMN_MONITORING_SETTINGS: "库存监控设置",
  LABEL_IS_MONITORED: "开启监控",
  LABEL_CHECK_INTERVAL_MIN: "检查间隔(分钟)",

  // New Smart Memo Labels
  SMART_MEMO_TITLE: "提醒备忘录",
  ADD_MEMO_BUTTON: "添加备忘",
  SMART_MEMO_PLACEHOLDER: "输入提醒，AI自动解析。如: 往'华东订单'添加'轴承A-123'明天提醒我",
  AI_PROCESSING: "AI正在解析...",
  NO_MEMOS: "暂无备忘录。输入一条新的备忘来开始吧！",
  DUE_DATE_LABEL: "截止于",
  RELATED_PART_LABEL: "关联零件",
  RELATED_ORDER_LABEL: "关联订单",
  ERROR_AI_PARSE: "AI解析失败，请检查您的输入或稍后再试。",
  ERROR_FETCHING_MEMOS: "加载备忘录失败。",
  ERROR_SAVING_MEMO: "保存备忘录失败。",
  ERROR_DELETING_MEMO: "删除备忘录失败。",
  ERROR_UPDATING_MEMO: "更新备忘录失败。",
  ERROR_EXECUTING_MEMO: "AI 执行备忘录失败。",
  AI_EXECUTE_BUTTON: "AI 执行",
  AI_EXECUTING: "AI 执行中...",
  AI_EXECUTE_CONFIRM_TITLE: "确认 AI 执行",
  AI_EXECUTE_CONFIRM_MSG: "您确定要让 AI 执行此任务吗？",
  
  // Admin Panel Labels
  ADMIN_DASHBOARD: "管理员后台",
  USER_MANAGEMENT: "用户管理",
  ORDER_MANAGEMENT: "订单管理",
  ADMIN_LOGOUT: "管理员登出",
  COLUMN_USER_ID: "用户ID",
  COLUMN_ROLE: "角色",
  COLUMN_CREATED_AT: "创建于",
  COLUMN_ORDER_OWNER: "所属用户",
  ACTION_EDIT_USER: "编辑用户",
  ACTION_DELETE_USER: "删除用户",
  CONFIRM_DELETE_USER_TITLE: "确认删除用户",
  CONFIRM_DELETE_USER_MSG: "您确定要彻底删除此用户及其所有数据（包括订单）吗？此操作无法撤销。",
  UPDATE_USER_TITLE: "更新用户信息",
  UPDATE_USER_SUCCESS: "用户更新成功。",
  UPDATE_USER_ERROR: "更新用户失败。",
  DELETE_USER_SUCCESS: "用户删除成功。",
  DELETE_USER_ERROR: "删除用户失败。",
  FORCE_DELETE_ORDER_TITLE: "确认强制删除订单",
  FORCE_DELETE_ORDER_MSG: "您确定要强制删除此订单吗？此操作将绕过回收站并立即永久删除，无法撤销。",
  FORCE_DELETE_ORDER_SUCCESS: "订单已强制删除。",
  FORCE_DELETE_ORDER_ERROR: "强制删除订单失败。",
  FETCH_USERS_ERROR: "加载用户列表失败。",
  FETCH_ORDERS_ERROR: "加载订单列表失败。",
  PASSWORD_LEAVE_BLANK: "留空则不修改密码",
  
  // New for Part Info Export
  PART_INFO_EXPORT_TITLE: "零件信息查询导出",
  PART_INFO_EXPORT_NOTE: "文件格式: 每行一个零件号 (TXT格式)。",
  PART_INFO_EXPORT_BUTTON: "上传TXT并导出",
  EXPORTING_PART_INFO: "正在查询并导出...",
  PART_INFO_EXPORT_SUCCESS: "零件信息导出成功！",
  PART_INFO_EXPORT_ERROR: "导出时发生错误。",
  PART_INFO_EXPORT_NO_PARTS: "文件中未找到可供查询的零件号。",
  PART_INFO_EXPORT_FILE_ERROR: "请选择一个有效的 TXT 文件。",

  // New for Quote Management
  QUOTE_MANAGEMENT_TITLE: "报价管理中心",
  QUOTE_MANAGEMENT_BUTTON: "报价管理",
  UPLOAD_HISTORY_TITLE: "上传历史报价",
  CUSTOMER_NAME_LABEL: "报价客户名称",
  CUSTOMER_NAME_PLACEHOLDER: "输入客户名称...",
  QUOTE_FILE_LABEL: "选择报价文件",
  QUOTE_FILE_NOTE: "格式: “零件号”, “人民币价格”, “备注” (Excel, 带表头)",
  UPLOAD_QUOTE_FILE_BUTTON: "上传报价文件",
  UPLOADING_QUOTE_FILE: "上传中...",
  UPLOAD_QUOTE_SUCCESS: "报价文件上传成功。",
  UPLOAD_QUOTE_ERROR: "报价文件上传失败。",
  SEARCH_QUOTES_TITLE: "报价查询与应用",
  SEARCH_QUOTES_PLACEHOLDER: "输入零件号进行模糊查询...",
  NO_QUOTE_RESULTS: "未找到相关的历史报价。",
  
  // Quote Inquiry
  CREATE_QUOTE_INQUIRY_TITLE: "创建新的报价单",
  CREATE_QUOTE_INQUIRY_NOTE: "格式: Excel文件, 第一列为零件号。",
  CREATE_QUOTE_INQUIRY_BUTTON: "上传文件并创建报价单",
  CREATING_QUOTE_INQUIRY: "正在创建报价单...",
  EXISTING_QUOTE_INQUIRIES: "历史报价单",
  NO_QUOTE_INQUIRIES: "暂无历史报价单。",
  QUOTE_INQUIRY_DETAILS_TITLE: "报价单详情",
  BACK_TO_QUOTE_MANAGEMENT: "返回报价管理",
  SELECT_A_QUOTE: "选择一条历史报价...",
  EXPORT_SELECTED_QUOTES_BUTTON: "导出现有选择 (Excel)",
  DELETE_QUOTE_INQUIRY_BUTTON: "删除报价单",
  CONFIRM_DELETE_QUOTE_INQUIRY_TITLE: "确认删除报价单",
  CONFIRM_DELETE_QUOTE_INQUIRY_MSG: "您确定要永久删除此报价单吗？此操作无法撤销。",
  COLUMN_ITEM_COUNT: "零件数",
  UPDATING_SELECTION: "正在保存选择...",
  SAVING_SELECTION_ERROR: "保存选择失败",
  COLUMN_QUERY_PART_NUMBER: "询价零件号",
  COLUMN_QUOTE_DATE: "报价日期",
  COLUMN_CUSTOMER_NAME: "客户名称",
  COLUMN_QUOTE_PRICE_RMB: "报价价格(RMB)",
  COLUMN_HISTORICAL_QUOTES: "历史报价记录",
};

export const LOCAL_STORAGE_TOKEN_KEY = "userToken"; 
export const MAX_NOTE_IMAGES = 5;
export const MAX_IMAGE_SIZE_MB = 2;